FROM resin/%%RESIN_MACHINE_NAME%%-python

RUN apt-get update && apt-get install -y raspi-gpio python-smbus libfreetype6-dev
RUN pip install inkyphat requests

COPY app/app.py /app.py
COPY app/assets /assets
COPY app/start.sh /start.sh

CMD ["bash", "start.sh"]

